# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

# 3. Gem settings
paginate: 2  # jekyll-paginate > items per page
paginate_path: bio/page:num  # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com  # jekyll-mentions > service used when @replying

# 4. Jekyll settings
sass:
  style: compressed  # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more -->  # Marks end of excerpt in posts
timezone: America/Guatemala  # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: "BIOS"  # Needed for Siteleaf
    output: true
    description: "Biografías cortas de los instructores"  # Description for the collection page
    feature_text: |
      ## Instructores  
    feature_image: "https://picsum.photos/2560/600?image=733"
  bios:
    output: true
    title: "Bios"
    description: "Biografías cortas de los instructores"
    feature_text: |
      ## Instructores
    feature_image: "https://picsum.photos/2560/600?image=733"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
    values:
      image: "{{ site.url }}{{ site.baseurl }}/assets/default-social-image.png"  # Default image for sharing
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post  # Set the default layout for posts
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page  # Set the default layout for pages
  - scope:
      path: ""
      type: "bios"
    values:
      layout: bio

# 7. Site settings
encoding: utf-8  # Make sure the encoding is right
lang: es  # Set the site language
title: "Taller mIF e IA"  # Site name or title
logo: "/assets/Imagenes/logoPagTallermIF_IA.png"  # Site logo
description: "Los asistentes se familiarizarán con los conceptos básicos de mIF y AI-DL..."  # Site description
url: "https://acnilo.github.io"  # Site url
baseurl: "/202411_LNMA_IA-mIF/"
repo: "https://github.com/acnilo/202411_LNMA_IA-mIF"
email: "chistopher.wood@ibt.unam.mx"

# 8. Site favicons & manifest icons
favicons:  # Favicons are also used in the manifest file
  16: '/assets/Imagenes/logoPagTallermIF_IA.png'
  32: '/assets/Imagenes/logoPagTallermIF_IA.png'
  96: '/assets/Imagenes/logoPagTallermIF_IA.png'
  120: '/assets/Imagenes/logoPagTallermIF_IA.png'
  144: '/assets/Imagenes/logoPagTallermIF_IA.png'
  180: '/assets/Imagenes/logoPagTallermIF_IA.png'
  512: '/assets/Imagenes/logoPagTallermIF_IA.png'
  1024: '/assets/Imagenes/logoPagTallermIF_IA.png'

# 9. Site navigation
navigation_header:
  - title: Inicio
    url: /
  - title: Programa
    url: /categories/
  - title: Instructores
    url: /bios/
  - title: Material del curso
    url: https://drive.google.com/drive/folders/1Jm9_aIGEk2-T0geeBIz_YFTtBhsBejt6?usp=sharing
    

navigation_footer:
  - title: Created by David Darnes
    url: https://darn.es

social_links:  # Appears in sidebar
  Twitter: https://twitter.com/lnma_mx
  LinkedIn: https://mx.linkedin.com/company/laboratorio-nacional-de-microscopía-avanzada-unam
  website: https://lnma.unam.mx/wp/
  galileo: https://www.galileo.edu/

sharing_links:  # Appear at the bottom of single blog posts
  Twitter: "#0d94e7"
  facebook: "#3B5998"
  Email: true

# Load custom fonts from fonts.google.com etc
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Merriweather:wght@400;700&display=swap
